name: SA54_lyeow_cicdWorkshop
on: 
  push: 
    tags:
      - 'v*'
jobs: 
  docker:
    runs-on: ubuntu-latest
    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: sa54lyeow/rndnum:${{ github.ref_name }}
  slack:
    runs-on: ubuntu-latest
    env:
      INCOMING_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    steps:
    - name: Slack Notification
      uses: tokorom/action-slack-incoming-webhook@main
      with:
        text: "${{ secrets.SLACK_PERSONALINFO }}\nRepo: ${{ github.repositoryUrl }}\nImage name: ${{ secrets.DOCKERHUB_ACCOUNT }}/rndnum:{{ github.ref_name }}\nImage url: https://hub.docker.com/repository/docker/${{ secrets.DOCKERHUB_ACCOUNT }}/rndnum"