name: SA54_lyeow_cicdWorkshop
on: 
  push: 
    branches:
    tags:
    - 'v*'
jobs: 
  docker:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: ${{ secrets.DOCKERHUB_ACCOUNT }}/rndnum:{{ github.ref_name }}
  slack:
    runs-on: ubuntu-latest
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
    steps:
    - name: Send custom JSON data to Slack workflow
      id: slack
      uses: slackapi/slack-github-action@v1.18.0
      with:
        # For posting a rich message using Block Kit
        payload: |
          {
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "Name: Yeow Jun Rong Leon"
                },
                "text": {
                  "type": "mrkdwn",
                  "text": "Matriculation: A0249491U"
                }, 
                "text": {
                  "type": "mrkdwn",
                  "text": "e0941684@u.nus.edu"
                },
                "text": {
                  "type": "mrkdwn",
                  "text": "${{ github.repositoryUrl }}"
                },
                "text": {
                  "type": "mrkdwn",
                  "text": "${{ secrets.DOCKERHUB_ACCOUNT }}/rndnum:{{ github.ref_name }}"
                },
                "text": {
                  "type": "mrkdwn",
                  "text": "Image url: https://hub.docker.com/repository/docker/${{ secrets.DOCKERHUB_ACCOUNT }}/rndnum"
                }
              }
          }
            ]
          }
